author:
  name: "Saeyan Yun"
  avatar: "/assets/images/bio-photo.png"
  bio: "Ph.D. Candidate in Measurement & Statistics at FSU."
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:saeyan.yun.ds@gmail.com"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.com/citations?user=PzE6WAgAAAAJ"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/saeyanyun"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/saeyanyun"

include:
  - _pages

plugins:
  - jekyll-include-cache
