author:
  avatar: "bio-photo.png"
  name: "Saeyan Yun"
  bio: "Ph.D. Candidate in Measurement & Statistics at FSU."
  email: "syun2@fsu.edu"
 
  googlescholar: "https://scholar.google.com/citations?user=PzE6WAgAAAAJ"
  orcid: "https://orcid.org/0009-0008-0314-3038"
  researchgate: "https://www.researchgate.net/profile/Saeyan-Yun?ev=hdr_xprf"
  github: "saeyanyun"
  linkedin: "saeyanyun"



include:
  - _pages

plugins:
  - jekyll-include-cache
